### PR TITLE
Add .nvmrc files to enforce requirements

### PR DESCRIPTION
**Pull request by chevdor**

### CODE REVIEW

**Comment by bestbeforetoday** [comment]
You will need to include a sign-off line in the commit message to make the DCO check happy. See [here](https://github.com/probot/dco#how-it-works). You should get the correct result by using `git commit -s`.

Please could you also include information on the reason for the change, such the problem it is addressing and how it solving it, or what new functionality is being added. Ideally this might be captured in a issue in the [composer project](https://github.com/hyperledger/composer) and the comments here would contain a reference to the issue.

**Comment by bestbeforetoday** [comment]
@chevdor Looking at the commit message I can see what this pull request is about now. Two things:
1. We are in the process of bumping the Node version to the latest LTS release (v8).
1. I have run `npm test` with both Node v6.11.5 and v8.9.0, and they both run fine, so it isn't clear to me the value in setting a specific Node version in a `.nvmrc`

**Comment by chevdor** [comment]
@bestbeforetoday happy to read that. I would consider the value in nvmrc as a recommandation from the project maintainers. If you say that 8.9.0 works fine, you will probably tend to recommend it.

Instead of writing this down and burry the info somewhere in the doc, having a .nmvrc file guides users. Now if a user, for any reason, wants to use another version, there are still free to do so of course.

Having the value in .nvmrc ensure (lazy) users that they use the project within specs. 
Usually, old versions of node are not supported, this is clear. My initial experience with composer was very bad, just because I used NodeJS v9.x.

With a .nvmrc file, I could have simply used 'nvm use' and I would have been within specs.

**Comment by davidkel** [comment]
closing as no activity.

**Comment by chevdor** [comment]
What alternate solution was chosen? In other words, how does a user which version to use?

**Pull request closed without merging**
